# Generated by Django 3.2.10 on 2022-02-15 09:56

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_alter_shopuser_activation_key_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 2, 17, 9, 56, 34, 424585, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
